name: Generate API

on: push

jobs:
  generate-api:
    runs-on: ubuntu-latest
    env:
      LIB_NAME: ${{ secrets.LIB_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install sdRDM
        run: python3 -m pip install git+https://github.com/JR-1991/software-driven-rdm.git@linking-refactor
        
      - name: Generate API
        env:
          URL: ${{github.repositoryUrl}}
          COMMIT: ${{github.sha}}
        run: sdrdm generate --path ./specifications/ --out . --name "$LIB_NAME" --url "$URL" --commit "$COMMIT"

      - name: Push source code
        run: |
          git add "$LIB_NAME"
          git config --global user.name 'sdRDM Bot'
          git config --global user.email 'sdRDM@bot.com'
          git commit -am "API update"
          git push
